// generated by scripts/tmp_test/web_videos/real_export.py; physical-robot trials per object
window.REAL = {
 "box": [
  {
   "src": "videos/real2x/box_1.mp4",
   "poster": "videos/real2x/box_1.jpg",
   "seconds": 15
  },
  {
   "src": "videos/real2x/box_2.mp4",
   "poster": "videos/real2x/box_2.jpg",
   "seconds": 15
  },
  {
   "src": "videos/real2x/box_3.mp4",
   "poster": "videos/real2x/box_3.jpg",
   "seconds": 30
  },
  {
   "src": "videos/real2x/box_4.mp4",
   "poster": "videos/real2x/box_4.jpg",
   "seconds": 17
  },
  {
   "src": "videos/real2x/box_5.mp4",
   "poster": "videos/real2x/box_5.jpg",
   "seconds": 20
  },
  {
   "src": "videos/real2x/box_6.mp4",
   "poster": "videos/real2x/box_6.jpg",
   "seconds": 24
  },
  {
   "src": "videos/real2x/box_7.mp4",
   "poster": "videos/real2x/box_7.jpg",
   "seconds": 17
  },
  {
   "src": "videos/real2x/box_8.mp4",
   "poster": "videos/real2x/box_8.jpg",
   "seconds": 25
  },
  {
   "src": "videos/real2x/box_9.mp4",
   "poster": "videos/real2x/box_9.jpg",
   "seconds": 42
  },
  {
   "src": "videos/real2x/box_10.mp4",
   "poster": "videos/real2x/box_10.jpg",
   "seconds": 46
  }
 ],
 "tape": [
  {
   "src": "videos/real2x/tape_1.mp4",
   "poster": "videos/real2x/tape_1.jpg",
   "seconds": 17
  },
  {
   "src": "videos/real2x/tape_2.mp4",
   "poster": "videos/real2x/tape_2.jpg",
   "seconds": 18
  },
  {
   "src": "videos/real2x/tape_3.mp4",
   "poster": "videos/real2x/tape_3.jpg",
   "seconds": 24
  },
  {
   "src": "videos/real2x/tape_4.mp4",
   "poster": "videos/real2x/tape_4.jpg",
   "seconds": 30
  },
  {
   "src": "videos/real2x/tape_5.mp4",
   "poster": "videos/real2x/tape_5.jpg",
   "seconds": 35
  },
  {
   "src": "videos/real2x/tape_6.mp4",
   "poster": "videos/real2x/tape_6.jpg",
   "seconds": 18
  },
  {
   "src": "videos/real2x/tape_7.mp4",
   "poster": "videos/real2x/tape_7.jpg",
   "seconds": 20
  },
  {
   "src": "videos/real2x/tape_8.mp4",
   "poster": "videos/real2x/tape_8.jpg",
   "seconds": 22
  },
  {
   "src": "videos/real2x/tape_9.mp4",
   "poster": "videos/real2x/tape_9.jpg",
   "seconds": 22
  },
  {
   "src": "videos/real2x/tape_10.mp4",
   "poster": "videos/real2x/tape_10.jpg",
   "seconds": 23
  }
 ],
 "bottle": [
  {
   "src": "videos/real2x/bottle_1.mp4",
   "poster": "videos/real2x/bottle_1.jpg",
   "seconds": 14
  },
  {
   "src": "videos/real2x/bottle_2.mp4",
   "poster": "videos/real2x/bottle_2.jpg",
   "seconds": 15
  },
  {
   "src": "videos/real2x/bottle_3.mp4",
   "poster": "videos/real2x/bottle_3.jpg",
   "seconds": 17
  },
  {
   "src": "videos/real2x/bottle_4.mp4",
   "poster": "videos/real2x/bottle_4.jpg",
   "seconds": 18
  },
  {
   "src": "videos/real2x/bottle_5.mp4",
   "poster": "videos/real2x/bottle_5.jpg",
   "seconds": 20
  },
  {
   "src": "videos/real2x/bottle_6.mp4",
   "poster": "videos/real2x/bottle_6.jpg",
   "seconds": 28
  },
  {
   "src": "videos/real2x/bottle_7.mp4",
   "poster": "videos/real2x/bottle_7.jpg",
   "seconds": 12
  },
  {
   "src": "videos/real2x/bottle_8.mp4",
   "poster": "videos/real2x/bottle_8.jpg",
   "seconds": 19
  },
  {
   "src": "videos/real2x/bottle_9.mp4",
   "poster": "videos/real2x/bottle_9.jpg",
   "seconds": 23
  },
  {
   "src": "videos/real2x/bottle_10.mp4",
   "poster": "videos/real2x/bottle_10.jpg",
   "seconds": 21
  }
 ],
 "stapler": [
  {
   "src": "videos/real2x/stapler_1.mp4",
   "poster": "videos/real2x/stapler_1.jpg",
   "seconds": 14
  },
  {
   "src": "videos/real2x/stapler_2.mp4",
   "poster": "videos/real2x/stapler_2.jpg",
   "seconds": 15
  },
  {
   "src": "videos/real2x/stapler_3.mp4",
   "poster": "videos/real2x/stapler_3.jpg",
   "seconds": 18
  },
  {
   "src": "videos/real2x/stapler_4.mp4",
   "poster": "videos/real2x/stapler_4.jpg",
   "seconds": 20
  },
  {
   "src": "videos/real2x/stapler_5.mp4",
   "poster": "videos/real2x/stapler_5.jpg",
   "seconds": 26
  },
  {
   "src": "videos/real2x/stapler_6.mp4",
   "poster": "videos/real2x/stapler_6.jpg",
   "seconds": 17
  },
  {
   "src": "videos/real2x/stapler_7.mp4",
   "poster": "videos/real2x/stapler_7.jpg",
   "seconds": 21
  },
  {
   "src": "videos/real2x/stapler_9.mp4",
   "poster": "videos/real2x/stapler_9.jpg",
   "seconds": 39
  },
  {
   "src": "videos/real2x/stapler_10.mp4",
   "poster": "videos/real2x/stapler_10.jpg",
   "seconds": 47
  },
  {
   "src": "videos/real2x/stapler_11.mp4",
   "poster": "videos/real2x/stapler_11.jpg",
   "seconds": 54
  }
 ],
 "spoon": [
  {
   "src": "videos/real2x/spoon_1.mp4",
   "poster": "videos/real2x/spoon_1.jpg",
   "seconds": 19
  },
  {
   "src": "videos/real2x/spoon_2.mp4",
   "poster": "videos/real2x/spoon_2.jpg",
   "seconds": 16
  },
  {
   "src": "videos/real2x/spoon_3.mp4",
   "poster": "videos/real2x/spoon_3.jpg",
   "seconds": 17
  },
  {
   "src": "videos/real2x/spoon_4.mp4",
   "poster": "videos/real2x/spoon_4.jpg",
   "seconds": 26
  },
  {
   "src": "videos/real2x/spoon_5.mp4",
   "poster": "videos/real2x/spoon_5.jpg",
   "seconds": 32
  },
  {
   "src": "videos/real2x/spoon_7.mp4",
   "poster": "videos/real2x/spoon_7.jpg",
   "seconds": 20
  },
  {
   "src": "videos/real2x/spoon_8.mp4",
   "poster": "videos/real2x/spoon_8.jpg",
   "seconds": 26
  },
  {
   "src": "videos/real2x/spoon_9.mp4",
   "poster": "videos/real2x/spoon_9.jpg",
   "seconds": 46
  },
  {
   "src": "videos/real2x/spoon_10.mp4",
   "poster": "videos/real2x/spoon_10.jpg",
   "seconds": 26
  },
  {
   "src": "videos/real2x/spoon_11.mp4",
   "poster": "videos/real2x/spoon_11.jpg",
   "seconds": 44
  }
 ]
};
