// generated by scripts/tmp_test/web_videos/web_export.py; labels for the text-free rollout clips
window.ROLLOUTS = [
 {
  "id": "ours_00",
  "section": "ours",
  "group": "bin",
  "scene": "bin",
  "arms": [
   "pol"
  ],
  "held": [
   true
  ],
  "src": "videos/rollouts/ours_00.mp4",
  "poster": "videos/rollouts/ours_00.jpg"
 },
 {
  "id": "ours_01",
  "section": "ours",
  "group": "bin",
  "scene": "bin",
  "arms": [
   "pol"
  ],
  "held": [
   true
  ],
  "src": "videos/rollouts/ours_01.mp4",
  "poster": "videos/rollouts/ours_01.jpg"
 },
 {
  "id": "ours_02",
  "section": "ours",
  "group": "edge",
  "scene": "edge",
  "arms": [
   "pol"
  ],
  "held": [
   true
  ],
  "src": "videos/rollouts/ours_02.mp4",
  "poster": "videos/rollouts/ours_02.jpg"
 },
 {
  "id": "ours_03",
  "section": "ours",
  "group": "edge",
  "scene": "edge",
  "arms": [
   "pol"
  ],
  "held": [
   true
  ],
  "src": "videos/rollouts/ours_03.mp4",
  "poster": "videos/rollouts/ours_03.jpg"
 },
 {
  "id": "ours_04",
  "section": "ours",
  "group": "ramp",
  "scene": "ramp",
  "arms": [
   "pol"
  ],
  "held": [
   true
  ],
  "src": "videos/rollouts/ours_04.mp4",
  "poster": "videos/rollouts/ours_04.jpg"
 },
 {
  "id": "ours_05",
  "section": "ours",
  "group": "ramp",
  "scene": "ramp",
  "arms": [
   "pol"
  ],
  "held": [
   true
  ],
  "src": "videos/rollouts/ours_05.mp4",
  "poster": "videos/rollouts/ours_05.jpg"
 },
 {
  "id": "ours_06",
  "section": "ours",
  "group": "ridge",
  "scene": "ridge",
  "arms": [
   "pol_s1"
  ],
  "held": [
   true
  ],
  "src": "videos/rollouts/ours_06.mp4",
  "poster": "videos/rollouts/ours_06.jpg"
 },
 {
  "id": "ours_07",
  "section": "ours",
  "group": "ridge",
  "scene": "ridge",
  "arms": [
   "pol"
  ],
  "held": [
   true
  ],
  "src": "videos/rollouts/ours_07.mp4",
  "poster": "videos/rollouts/ours_07.jpg"
 },
 {
  "id": "ours_08",
  "section": "ours",
  "group": "composite_a",
  "scene": "composite_a",
  "arms": [
   "v5"
  ],
  "held": [
   true
  ],
  "src": "videos/rollouts/ours_08.mp4",
  "poster": "videos/rollouts/ours_08.jpg"
 },
 {
  "id": "ours_09",
  "section": "ours",
  "group": "composite_b",
  "scene": "composite_b",
  "arms": [
   "v5"
  ],
  "held": [
   true
  ],
  "src": "videos/rollouts/ours_09.mp4",
  "poster": "videos/rollouts/ours_09.jpg"
 },
 {
  "id": "ours_10",
  "section": "ours",
  "group": "counter_bs",
  "scene": "counter_bs",
  "arms": [
   "v5"
  ],
  "held": [
   true
  ],
  "src": "videos/rollouts/ours_10.mp4",
  "poster": "videos/rollouts/ours_10.jpg"
 },
 {
  "id": "ours_11",
  "section": "ours",
  "group": "dish_rack_lg",
  "scene": "dish_rack_lg",
  "arms": [
   "v5"
  ],
  "held": [
   true
  ],
  "src": "videos/rollouts/ours_11.mp4",
  "poster": "videos/rollouts/ours_11.jpg"
 },
 {
  "id": "ours_12",
  "section": "ours",
  "group": "drainboard_lg",
  "scene": "drainboard_lg",
  "arms": [
   "v5"
  ],
  "held": [
   true
  ],
  "src": "videos/rollouts/ours_12.mp4",
  "poster": "videos/rollouts/ours_12.jpg"
 },
 {
  "id": "ours_13",
  "section": "ours",
  "group": "flat_slab",
  "scene": "flat_slab",
  "arms": [
   "v5"
  ],
  "held": [
   true
  ],
  "src": "videos/rollouts/ours_13.mp4",
  "poster": "videos/rollouts/ours_13.jpg"
 },
 {
  "id": "ours_14",
  "section": "ours",
  "group": "organizer_lg",
  "scene": "organizer_lg",
  "arms": [
   "v5"
  ],
  "held": [
   true
  ],
  "src": "videos/rollouts/ours_14.mp4",
  "poster": "videos/rollouts/ours_14.jpg"
 },
 {
  "id": "ours_15",
  "section": "ours",
  "group": "sink_slabw",
  "scene": "sink_slabw",
  "arms": [
   "v5"
  ],
  "held": [
   true
  ],
  "src": "videos/rollouts/ours_15.mp4",
  "poster": "videos/rollouts/ours_15.jpg"
 }
];
